-- mas-ai-advisor Phase 0
-- Create the mas_journey_* foundation tables in the MAS Postgres `mas` database.
-- These telemetry tables are shared across all MAS journey-tracking scopes
-- (mas-public-advisor, future maintenance-assistant scopes, etc.); mas-ai-advisor
-- is the first consumer but does not own them exclusively.
--
-- Apply BEFORE 001_add_install_consent_columns.sql.
--
-- Schema sourced from:
--   * BrianPKM ~/gdrive-brianpkm/3-Resources/mas-ai-advisor-spec.md § Data Model
--   * lib/schemas.ts (zod request shapes)
--   * app/api/install/register/route.ts + app/api/conversation/{turn,private}/route.ts
--     (the actual INSERT/SELECT/DELETE column references)
--
-- email and share_history are intentionally NOT created here — they are added
-- by 001_add_install_consent_columns.sql so the v1 migration history reflects
-- the spec narrative ("the existing table gains two consent columns").

BEGIN;

-- Installs: one row per (install_id) registration. install_id is generated by
-- the Advisor on first turn and supplied by the client, so it is the PK rather
-- than a server-generated surrogate. scope partitions installs across multiple
-- MAS journey-tracking products sharing this table.
CREATE TABLE IF NOT EXISTS mas_journey_installs (
  install_id  UUID        PRIMARY KEY,
  scope       TEXT        NOT NULL,
  platform    TEXT        NOT NULL,
  source      TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS mas_journey_installs_scope_idx
  ON mas_journey_installs (scope);

-- Events: append-only telemetry log keyed by install. Rows for a given
-- conversation_id can be deleted in bulk via the /conversation/private
-- endpoint (matches payload->>'conversation_id'); no other deletes expected.
-- No FK to mas_journey_installs.install_id by design — events may be written
-- by code paths that skip the install record (and the /turn endpoint already
-- guards by SELECTing the install first).
CREATE TABLE IF NOT EXISTS mas_journey_events (
  id          BIGSERIAL   PRIMARY KEY,
  install_id  UUID        NOT NULL,
  scope       TEXT        NOT NULL,
  event_type  TEXT        NOT NULL,
  payload     JSONB,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Supports the /conversation/private DELETE filter (install_id + event_type)
-- and the typical "all events for this install" query pattern.
CREATE INDEX IF NOT EXISTS mas_journey_events_install_id_event_type_idx
  ON mas_journey_events (install_id, event_type);

-- Supports cross-scope reporting queries.
CREATE INDEX IF NOT EXISTS mas_journey_events_scope_idx
  ON mas_journey_events (scope);

-- Sanity check: confirm install_id is uniquely constrained so /register's
-- ON CONFLICT (install_id) DO NOTHING works as intended. Must return ≥1 row.
SELECT conname, contype
FROM pg_constraint
WHERE conrelid = 'mas_journey_installs'::regclass
  AND contype IN ('p', 'u');

COMMIT;
